language: rust
rust:
  - stable
  - beta
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
install: |
  pip install 'travis-cargo<0.2' --user &&
  (cargo install rustfmt || true) &&
  export PATH=$HOME/.local/bin:$PATH &&
  export PATH=$HOME/.cargo/bin:$PATH
script: |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test &&
  travis-cargo --only stable doc
after_success: |
  travis-cargo --only stable doc-upload &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/feed &&
  echo "Uploaded code coverage"
env:
  global:
    - secure: eCyV4mrlVXjY7CRHMMzHxjXIJPn4pcjoOGTiT0zAS6AutWXs64OVtAB7zmvPjlMuarXPG8YmR3DIrdLc9tcG6eQHSTBw1Xp23L+/DPyklGVYZrHs9QNWIPkTLk9ezdJUZvgQzJvM4wTRiynxSk9usWbsh+51RM9pCYD8cWrimnQp35FCtXGIa24WlQO4fRHprjvYMtwRoBl8nIuFMWGPsbKOICjQgXUkJ8Ae/xqWzDQzz0BD4WHLfl1r90+tAATi2t0rXbhTjK4t+HQgiJRaKGvLauTdJTOcSPWp0lNKIBoCPUILA6mPCk+2fWfEK53ktcEvLCGvZBhXMzHSnT2bNwFHh6KBMaIRTgMz8LsLR4JXRllZapGD7xzsADfSH/L9YCyP/st/kbANklWFZiTkYMR5H2eDK4r1V71VYPgrwAv7XlWFGPYIsjywO3gfWT2wnO9dZaFIYFdFAl6CX4KkprmiDiAM5yjBvUA3HEaPUXecsKezPxlosWIe1V4Stc5o5oMAIruEcMLqBJ6Ut1GGtNFk7V6FW+7kNS5+CwdQ9h3Bzi3wVjK9CpL9Jl5iepPsXv3y+W9a5ZrsgwmLq9Fy2v8DjD0udFyxyDIzTqSKwBcBii70clcLK8JA7UVFGmQGRS2t7Jec7Y4smxRlQU3OA8JFWWJaYBWvyuoBCk4VHYc=
